# Generated by Django 4.1.5 on 2023-01-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("A", "Admin"), ("S", "Staff")], max_length=1
                    ),
                ),
                ("uid", models.IntegerField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
